package ch.battleship.battleshipbackend.domain.common;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * Base class for JPA entities providing a UUID identifier and audit timestamps.
 *
 * <p>This mapped superclass is inherited by concrete entity classes to ensure a consistent
 * persistence model across the application.
 *
 * <p>Audit fields:
 * <ul>
 *   <li>{@code createdAt} is set once when the entity is first persisted.</li>
 *   <li>{@code updatedAt} is refreshed on every update.</li>
 * </ul>
 */
@MappedSuperclass
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public abstract class BaseEntity {

    /**
     * Primary key generated by JPA/Hibernate.
     */
    @Id
    @GeneratedValue
    private UUID id;

    /**
     * Timestamp of entity creation. Set once and not updated afterwards.
     */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp of last update. Refreshed on every update.
     */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * JPA lifecycle callback executed before the entity is persisted for the first time.
     *
     * <p>Initializes {@code createdAt} and {@code updatedAt} with the current timestamp.
     */
    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback executed before an entity update is written to the database.
     *
     * <p>Updates {@code updatedAt} with the current timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
